# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib mirtjml
#' @importFrom Rcpp evalCpp
NULL

#' @export
alter_mini_CJMLE_cpp <- function(response, nonmis_ind, theta0, A0, C, tol, print_proc) {
    .Call('_mirtjml_alter_mini_CJMLE_cpp', PACKAGE = 'mirtjml', response, nonmis_ind, theta0, A0, C, tol, print_proc)
}

